### ISSUE TITLE
[DoomMake] Automatically create patch/texture from single image

### ISSUE THREAD

**Issue by biwa** [MTrop/DoomTools#58]
Right now to create a texture with the "textures" template you have to add the patch(es) and then edito the `texture1.txt` or `texture2.txt` file to create a texture from the patch(es).

Many custom textures are only composed of a single patch, though, so it'd be nice to be able to let DoomMake automatically create a patch and the corrosponding texture definition from a single file. Those single images could be placed in a dedicated directory, for example:

- src/convert/textures
- src/textures/textures

The patch and texture could have the same name as the file. There's the danger of the user having a file of the same name in the `patches` *and* `textures` directory, but I guess DoomMake should warn the user about that.

**Comment by MTrop** [comment]
Hmmm. I wonder if the WadMerge script created to merge the texture resource together could be leveraged for this, since that contains a mechanism for merging in a directory of textures. 

It's very doable, but I'll have to take a look to determine the best approach. Maybe the texture directories should be merged in after the DEUTex merge, so that you can still add a null texture?

**Comment by MTrop** [comment]
Added in commit 09b85a8
