### ISSUE TITLE
NoSuchMethodError when compiling DecoHack

### ISSUE THREAD

**Issue by skillsawed** [MTrop/DoomTools#8]
I was attempting to compile this DecoHack (with the latest release):

`
#include "classpath:decohack/extended.dh"
ammo 0 "Hello World"
{
  max 300
  pickup 20
}
`

With this command:
`decohack src/decohack/root.dh -o src/misc/dehacked.txt -b`

And getting this output:

--- Patch State Budget ---
States: 1089 used / 4000 total (2911 remaining).
--------------------------
Exception in thread "main" java.lang.NoSuchMethodError: java.io.FileWriter.<init>(Ljava/io/File;Ljava/nio/charset/Charset;)V                                                                                  io/charset/Charset;)V
        at net.mtrop.doom.tools.DecoHackMain$Context.call(DecoHackMain.java:285)
        at net.mtrop.doom.tools.DecoHackMain.call(DecoHackMain.java:400)
        at net.mtrop.doom.tools.DecoHackMain.main(DecoHackMain.java:414)

I pulled down the latest source, compiled it, and ran into the same issue.

I worked around the issue locally by changing the FileWriter constructor in DecoHackMain.java and recompiling:

`
// Write Patch.
try (Writer writer = new FileWriter(options.outFile))
`

**Comment by MTrop** [comment]
It looks like the constructor that takes a `Charset` was added in a version of Java later than 8. Since I am targeting Java 8 with these tools, this is indeed an issue.

I'll probably need to change the `FileWriter` to an [OutputStreamWriter](https://docs.oracle.com/javase/8/docs/api/java/io/OutputStreamWriter.html) that wraps a `FileOutputStream`. The use of `FileWriter` caught me off guard - I usually don't use `FileReader` or `FileWriter` normally. Lack of sleep will do that, heh.

In dialing back the targeted Java version, I'll have to also fix how I'm doing an `FFmpeg` process call in DMXConvert. All in all, a pretty simple fix.

**Comment by MTrop** [comment]
Fixed in commit https://github.com/MTrop/DoomTools/commit/7cb466105961650e051380a59ac1a7072eb7d008
